random forest - MULTICLASS CLASSFICATION

In [50]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
sns.set()

In [2]:
data = pd.read_csv('Digital recognition.csv')

In [3]:
data.head()

Unnamed: 0    0    1    2     3     4     5    6    7    8  ...   55   56  \
0           0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  ...  0.0  0.0   
1           1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  ...  0.0  0.0   
2           2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  ...  0.0  0.0   
3           3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  ...  0.0  0.0   
4           4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   

    57   58    59    60    61   62   63  target  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 66 columns]

In [4]:
data.describe()

Unnamed: 0       0            1            2            3  \
count  1797.000000  1797.0  1797.000000  1797.000000  1797.000000   
mean    898.000000     0.0     0.303840     5.204786    11.835838   
std     518.893534     0.0     0.907192     4.754826     4.248842   
min       0.000000     0.0     0.000000     0.000000     0.000000   
25%     449.000000     0.0     0.000000     1.000000    10.000000   
50%     898.000000     0.0     0.000000     4.000000    13.000000   
75%    1347.000000     0.0     0.000000     9.000000    15.000000   
max    1796.000000     0.0     8.000000    16.000000    16.000000   

                 4            5            6            7            8  ...  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  ...   
mean     11.848080     5.781859     1.362270     0.129661     0.005565  ...   
std       4.287388     5.666418     3.325775     1.037383     0.094222  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%      10.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%      13.000000     4.000000     0.000000     0.000000     0.000000  ...   
75%      15.000000    11.000000     0.000000     0.000000     0.000000  ...   
max      16.000000    16.000000    16.000000    15.000000     2.000000  ...   

                55           56           57           58           59  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.206455     0.000556     0.279354     5.557596    12.089037   
std       0.984401     0.023590     0.934302     5.103019     4.374694   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     1.000000    11.000000   
50%       0.000000     0.000000     0.000000     4.000000    13.000000   
75%       0.000000     0.000000     0.000000    10.000000    16.000000   
max      13.000000     1.000000     9.000000    16.000000    16.000000   

                60           61           62           63       target  
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  
mean     11.809126     6.764051     2.067891     0.364496     4.490818  
std       4.933947     5.900623     4.090548     1.860122     2.865304  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%      10.000000     0.000000     0.000000     0.000000     2.000000  
50%      14.000000     6.000000     0.000000     0.000000     4.000000  
75%      16.000000    12.000000     2.000000     0.000000     7.000000  
max      16.000000    16.000000    16.000000    16.000000     9.000000  

[8 rows x 66 columns]

In [5]:
x = data.drop(['target'], axis=1)

# df.drop(['a', 'b'], axis=1)

In [6]:
x.head()

Unnamed: 0    0    1    2     3     4     5    6    7    8  ...   54   55  \
0           0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  ...  0.0  0.0   
1           1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  ...  0.0  0.0   
2           2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  ...  5.0  0.0   
3           3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  ...  9.0  0.0   
4           4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   

    56   57   58    59    60    61   62   63  
0  0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 65 columns]

In [31]:
x_scaled = preprocessing.scale(x)

In [32]:
x_scaled

array([[-1.73108722,  0.        , -0.33501649, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [-1.7291595 ,  0.        , -0.33501649, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [-1.72723179,  0.        , -0.33501649, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 1.72723179,  0.        , -0.33501649, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 1.7291595 ,  0.        , -0.33501649, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 1.73108722,  0.        , -0.33501649, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [33]:
#y = data.iloc[:, 65]
y = data['target']

In [34]:
y.describe()

count    1797.000000
mean        4.490818
std         2.865304
min         0.000000
25%         2.000000
50%         4.000000
75%         7.000000
max         9.000000
Name: target, dtype: float64

In [35]:
y.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [49]:
y.value_counts()

3    183
5    182
1    182
6    181
4    181
9    180
7    179
0    178
2    177
8    174
Name: target, dtype: int64

SELECTING 20% FOR TESTING AND 80% FOR TRAINING

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train, x_test, y_train, c =  train_test_split(x_scaled, y, test_size = 0.2)

NOW RUNNING THE MODEL RANDOM FOREST

In [59]:
model = RandomForestClassifier()

In [62]:
r = model.fit(x_train, y_train)

In [63]:
r

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [85]:
model.score(x_test, y_test)

0.9666666666666667

In [66]:
p = model.predict(x_test)

In [67]:
p.shape

(360,)

In [68]:
y_test.shape

(360,)

In [80]:
compare = pd.DataFrame()
compare['y_test'] = y_test
compare['predicting'] = p
compare['Matching'] = np.where(y_test == p, 1, 0)
compare.describe()

y_test  predicting    Matching
count  360.000000  360.000000  360.000000
mean     4.500000    4.525000    0.966667
std      2.901349    2.879074    0.179755
min      0.000000    0.000000    0.000000
25%      2.000000    2.000000    1.000000
50%      5.000000    5.000000    1.000000
75%      7.000000    7.000000    1.000000
max      9.000000    9.000000    1.000000

In [81]:
counts = (compare['Matching']==1).value_counts().to_dict()
counts

{True: 348, False: 12}

In [82]:
accuracy = counts[True]/(counts[True] + counts[False])

In [83]:
accuracy

0.9666666666666667

In [86]:
from sklearn.metrics import confusion_matrix

In [87]:
cm = confusion_matrix(p, y_test)
cm

array([[38,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 32,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 39,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 34,  0,  0,  0,  0,  1,  2],
       [ 1,  0,  0,  0, 26,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0, 32,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 41,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0, 40,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0,  0, 33,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0, 33]], dtype=int64)

In [84]:
#MAKING A DATAFRAME FOR THE CONFUSION MATRIX

cm_df = pd.DataFrame(cm)
cm_df.columns = ['P 0','P 1','P 2','P 3','P 4','P 5','P 6','P 7','P 8','P 9']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1',2:'Actual 2',3:'Actual 3',4:'Actual 4',5:'Actual 5',6:'Actual 6',7:'Actual 7',8:'Actual 8',9:'Actual 9'})
cm_df

P 0  P 1  P 2  P 3  P 4  P 5  P 6  P 7  P 8  P 9
Actual 0   38    0    0    0    0    0    0    0    0    0
Actual 1    0   32    0    0    0    0    0    0    0    0
Actual 2    0    0   39    0    0    0    0    0    0    0
Actual 3    0    0    0   34    0    0    0    0    1    2
Actual 4    1    0    0    0   26    1    0    0    0    0
Actual 5    0    0    0    1    0   32    0    0    0    1
Actual 6    0    0    0    0    0    0   41    0    0    0
Actual 7    0    0    0    2    0    0    0   40    0    0
Actual 8    0    0    0    2    0    0    0    0   33    0
Actual 9    0    0    1    0    0    0    0    0    0   33